### PR TITLE
fix: change extension name to Developer Sandbox

### LINKED ISSUE #278: Update product name
We should be updating the product name referenced in the application.
- extension name should be "Developer Sandbox for Red Hat Openshift" 
- description of the extension should also be updated
- similarly, in the UI of the extension
  - on the dashboard of podman desktop
  - in the resource page

### PR DESCRIPTION
**Pull request by dgolovin**
Update extension name to Developer Sandbox throughout the extension.

Fix #278,

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -295,7 +295,7 @@ function updateConnectionsPeriodically(): void {
 }
 
 export function deactivate(): void {
-  console.log('deactivating extension openshift-sandbox');
+  console.log('deactivating redhat-sandbox extension');
```
Comment (gastoner) [inline src/extension.ts:298]: redhat-developer-sandbox extension?

**Review by gastoner — APPROVED** [review]

File: src/extension.ts (hunk 1 above)
Comment (dgolovin) [reply src/extension.ts]: updated in activate and deactivate methods.
